language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t sparkitny/docker-react .
script:
  - docker run -e CI=true sparkitny/docker-react npm run test -- --coverage